### ISSUE TITLE
Fitz.open is not passing back exception

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [pymupdf/PyMuPDF-Optional-Material#2] opened 2017-11-17 06:42 UTC
My open call is quite simply:
doc = fitz.open(input_path + '\\' + file)

I'm experiencing crashes when corrupt PDF files are encountered.  I would be happy to pre-screen them if I knew what to look for.  I assumed that fitz.open would raise and exception that's passed back to me but instead it's crashing with this information:
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
warning: object missing 'endobj' token
error: non-page object in page tree
uncaught exception: non-page object in page tree

I'm attaching my PDF file that is causing the trouble.
I'm using this code to extract images from a large number of PDF files that I've generated using WKHTMLTOPDF.  I'm unsure why a few of them are corrupt.  I'm working on that end of things.

Is there a different way I can call the open that will cause the exception to be passed back to me so that I can skip the file and move on to the next?

Thank you for your time.

[1960s GRUEN Airflight Vintage Pilot Aviators Military Time Jump Hour Watch.pdf](https://github.com/JorjMcKie/PyMuPDF-Optional-Material/files/1481277/1960s.GRUEN.Airflight.Vintage.Pilot.Aviators.Military.Time.Jump.Hour.Watch.pdf)

**Comment by JorjMcKie** [comment] 2017-11-20 11:12
closed because it is a duplicate of https://github.com/rk700/PyMuPDF/issues/105.

**Closed as completed by JorjMcKie** 2017-11-20 11:12 UTC
